name: test and deploy

on:
  push:
    branches:
      - main

jobs:
  # unit test
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: List files
        run: ls -al

      - name: Test
        run: npm run test

  # build docker image
  # deploy