name: test and deploy

on:
  push:
    branches: main

jobs:
  # unit test
  unit-test:
    runs-on: ubuntu-latest
    steps:

      - name: clone repo
        uses: actions/checkout@v4

      - run: ls -al

      - name: test
        run: npm run test

  # build docker image
  # deploy