name : test and deploy

on:
    push:
         branches: main

jobs:
    # unit test 
    unit-test:
        runs-on: ubunto-latest
        steps:

            -name: clone repo 
            uses: actions/checkout@v7
            -run: ls -al
            -name: test 
            run: npm run test 
    # build docker image 
    # deploy
   